FROM maven:3.8.5-openjdk-17-slim

WORKDIR /LibraryProject2

COPY . .

RUN mvn clean package -DskipTests

CMD [ "mvn", "spring-boot:run" ]

# CMD ["java", "-jar", "/LibraryProject2/target/LibraryProject2-0.0.1-SNAPSHOT.jar"]
